import type { Metadata } from 'next';
import './globals.css';
import { Roboto } from 'next/font/google';
import Header from '@/components/Header/Header';
import css from '@/app/page.module.css';
// import { AuthProvider } from '@/auth-context';
// import { Toaster } from 'react-hot-toast';
import Providers from '@/components/Providers';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        {/* <AuthProvider> */}
        <Providers>
          <Header />
          {children}
        </Providers>
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
